### ISSUE TITLE
Please add tweetdeck

### ISSUE THREAD

**Issue by w8sdz** [luciomartinez/tweet-pure-links#1]
Please make this script work on https://tweetdeck.twitter.com

**Comment by luciomartinez** [comment]
Hello,

A new version is available on [OpenUserJS](https://openuserjs.org/scripts/lucio-martinez/Fix_Twitter_links). To update it just press install.

Please test it, I'm looking forward to hear feedback.

Regards

**Comment by w8sdz** [comment]
Lucio, thank you - it's working very well on Tweetdeck!

Have you considered posting this script to Greasyfork? I have a feeling that
it would be very popular there.

I'm surprised that prominent bloggers have not spread the word on this great
way to eliminate a Twitter annoyance.

73 de w8sdz

## Keith

Keith Petersen
w8sdz@Mail.Petersen.Net
https://twitter.com/w8sdz
https://plus.google.com/+w8sdz

**Comment by w8sdz** [comment]
Lucio, I have posted a Google+ share about your Fix Twitter Links script.
The posting will also appear on my Twitter page, Facebook profile page,
Tumblr blog, and Apt.net page.

Please look at https://plus.google.com/+w8sdz/posts/KCHhhDvfSLc to see the
posting.

This page https://plus.google.com/+w8sdz/about lists the URLs of the other
accounts.

Thanks again for your very useful User Script!

## Keith

Keith Petersen
w8sdz@Mail.Petersen.Net

**Comment by luciomartinez** [comment]
Hey Keith

Thank you so much for the support! I appreciate it.

I uploaded the script into Greasy Fork: https://greasyfork.org/en/scripts/16847-fix-twitter-links

Best regards, Lucio
